version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - 4567:4567
    secrets:
      - host_ssh_key

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
