source 'http://rubygems.org'

gem 'middleman', '4.3.8'
gem 'middleman-blog', '~> 4.0', '>= 4.0.2'
gem 'middleman-syntax'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-disqus', '~> 1.2'
gem 'pygments.rb', '~> 1.2', '>= 1.2.1'
gem 'nokogiri', '~> 1.6', '>= 1.6.7.1'
gem 'redcarpet'
gem 'builder', '~> 3.0'
gem 'middleman-livereload'
